// vue3/components/positioning/Center.vue
<template>
    <div :class='$style.container' :style='{height, width}'>
        <div><slot/></div>
    </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default {
    props: ['width', 'height']
}
</script>

<style lang="scss" module>
.container {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
}
</style>

// react/components/positioning/Center.tsx
import { PropsWithChildren } from "react";
import styles from '../../styles/components/positioning/Center.module.scss'

interface Props extends PropsWithChildren {
    height?: string,
    width?: string
}

export default function Center({children, height, width}: Props){
    return (<div className={styles.container} style={{height, width}}>
            <div>{children}</div>
        </div>)
}
